const router = require("express").Router();
const authRouter = require("./auth.js");
const userRouter = require("./users.js");
const roleRouter = require("./roles.js");
const ailmentRouter = require("./ailment.js");
const prescriptionRouter = require("./prescription.js");
const labReportRouter = require("./labreport.js");
const doctorRouter = require("./doctors.js");
const patientRouter = require("./patient.js");
const readingsRouter = require("./readings_table.js");
const requisitionRouter = require("./requisition.js");
const questionsRouter = require("./questions.js");
const alertsRouter = require("./alerts.js");
const mailRouter = require("./mail.js");
const languagesRouter = require("./Languages.js");
const userResponsesRouter = require("./userResponses.js");
const alarmsRouter = require("./alarmsRouter.js");
const graphReadingsRouter = require("./graphReadings.js");
const userRangeRouter = require("./userRange.js");
const chatRouter = require("./chatRouter.js");
const dietDetailsRouter = require("./dietdetails.js");
const manageparametersRouter = require("./manageparameters.js");
const appRouter = require("./app_apis.js");
const graphReadingDialysisRouter = require("./graphReadingDialysis.js");
const userRangeDialysisRouter = require("./userRangeDialysis.js");
const uploadRouter = require("./dataUpload.js");
const commentsRouter = require("./comments.js");
const AlertSortingRouter = require("./SortAlerts.js");
const doctorPatientRouter = require("./doctorPatient.js");
const adminPatientRouter = require("./adminPatient.js");
const ailmentPatientRouter = require("./ailmentPatient.js");
const pushNotifsRouter = require("./notifs.js");
const contactusRouter = require("./contactus.js");
const dailyAlertsRouter = require("./dailyAlerts.js");
const patientdatarouter = require("./patientdatarouter.js");
const teleconsultationRouter = require("./teleconsultation.js");
const analyticsRouter = require("./doctorAnalytics.js");
const moduleRoutes = require("./moduleRoutes.js");


router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/roles", roleRouter);
router.use("/ailment", ailmentRouter);
router.use("/prescription", prescriptionRouter);
router.use("/labreport", labReportRouter);
router.use("/doctor", doctorRouter);
router.use("/patient", patientRouter);
router.use("/readings", readingsRouter);
router.use("/requisition", requisitionRouter);
router.use("/questions", questionsRouter);
router.use("/alerts", alertsRouter);
router.use("/mail", mailRouter);
router.use("/languages", languagesRouter);
router.use("/userResponses", userResponsesRouter);
router.use("/alarms", alarmsRouter);
router.use("/readings", graphReadingsRouter);
router.use("/range", userRangeRouter);
router.use("/chat", chatRouter);
router.use("/dietdetails", dietDetailsRouter);
router.use("/manageparameters", manageparametersRouter);
router.use("/app", appRouter);
router.use("/dialysisReading", graphReadingDialysisRouter);
router.use("/rangeDialysis", userRangeDialysisRouter);
router.use("/sortAlerts", AlertSortingRouter);
router.use("/upload", uploadRouter);
router.use("/comments", commentsRouter);
router.use("/assignedDoctor", doctorPatientRouter);
router.use("/assignedAdmin", adminPatientRouter);
router.use("/ailmentPatient", ailmentPatientRouter);
router.use("/notifs", pushNotifsRouter);
router.use("/contactus", contactusRouter);
router.use("/dailyAlerts", dailyAlertsRouter);
router.use("/patientdata", patientdatarouter);
router.use("/teleconsultation",teleconsultationRouter);
router.use("/analytics",analyticsRouter);
router.use("/moduleConnection",moduleRoutes);


module.exports = router;
